### ISSUE TITLE
Rego Band Switching without MFC and/or Meter

### ISSUE THREAD

**Issue by N8VET** [w4mmp/MSCC-PW#12]
**Describe the bug**
Rego band switching does not work unless you have MFC or Meter attached.  Works great when I connected the MFC and re-ran mscc-pw-cfg.

I have been using the Ultimus for Amplifier testing which has it's own band switching jack but was wanting to try out the Proficio using the Rego Band switching without having to connect everything else up.

I suppose most folks with a Rego would have at least an MFC so my situation might be a rare setup;)
Stew
N8VET

**MSCC-PW release date (please complete the following information):**
20220903

**Desktop (please complete the following information):**
 - OS: Win 8  It works :)

**Comment by w4mmp** [comment]
Hi Stew,
I never considered that an option ;).  Why would someone have a Rego without the MFC and/or the power meter?  I will take a look.

**Comment by w4mmp** [comment]
Hi Stew,
This has been fixed.  The Rego band switching is now active even if the MFC and/or the power meter are not present.
New release on the Google drive.
73,
Ron
