### ISSUE TITLE
Proficio Fan does not seem to function

### ISSUE THREAD

**Issue by JazzmanRick** [w4mmp/MSCC-PW#14]
**Describe the bug**
Fan never seems to come on though so far have only operated on CW

**MSCC-PW current release

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by w4mmp** [comment]
Hi Rick,
MSCC-PW has no control of the fan.  It is controlled by the transceiver hardware.  (I assume this is a Proficio or Ultimus). Please make a post on the forum regarding this.
73,
Ron

**Comment by JazzmanRick** [comment]
Yes this is an older Proficio and the fan is not functioning, though I think it did with older software. Hardware problem?
Rick, W2JAZ

**Comment by JazzmanRick** [comment]
I still see no fan activity when I run my Proficio. Maybe it would in a keydown mode like FT8 or PSK31 but I don't think there is a way to know the temp and when it should cycle on and off. Any thoughts out there?

Rick
