### ISSUE TITLE
Frequency manual calibration

### ISSUE THREAD

**Issue by N8VET** [w4mmp/MSCC-PW#15]
**Describe the bug**
The little square box to the right of the entered(desired frequency) frequency is missing so manual calibration will not work.

**To Reproduce**

**Expected behavior**

**Screenshots**

**MSCC-PW release date (please complete the following information):**
[e.q. 20220906]

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]

**Additional context**

**Comment by N8VET** [comment]
Noticed I didn't have the latest release, now it is 20220907 with same issue.

**Comment by w4mmp** [comment]
Hi Stew,
The issue has been fixed.  Simply enter the frequency in the target box and it will be applied when doing a manual calibration.
New release on the Google Drive.
73,
Ron
