### ISSUE TITLE
AM Carrier Level setting not maintained after MSCC-PW restart.

### ISSUE THREAD

**Issue by Bob-TX** [w4mmp/MSCC-PW#16]
**Describe the bug**
The AM Carrier Level setting on the Rx/Tx tab is not saved and restored during MSCC-PW exit/stop and re-start.

**To Reproduce**
1. Run MSCC-PW. Click Rx/Tx tab and observe AM Carrier Level setting is centered at 50%.
2. Click on AM Carrier Level adjustment and change setting to a different setting (25% used in this example).
3. Click on Main tab and then Rx/Tx tab and observe AM Carrier Level adjustment shows chosen previous setting (25% in this example).
4. Click on Main tab and then click on EXT and choose STOP to close MSCC-PW.
5. Run MSCC-PW. Click Rx/Tx tab and observe AM Carrier Level setting is centered at 50%.

**Expected behavior**
I expected whatever setting I choose for AM Carrier Level would be saved and restored after MSCC-PW was exited/stopped and then re-started.

**MSCC-PW release date (please complete the following information):**
MSCC 09/07/2022

**Desktop (please complete the following information):**
 - OS: Windows 10 Home

**Comment by w4mmp** [comment]
Hi Bob,
I will be working on your issues in the coming week.
73,
Ron

**Comment by w4mmp** [comment]
This issue has been resolved.   New release on the Google Drive: MSCC-PW-Install-20220919.exe
73,
Ron
