### ISSUE TITLE
Enhanced waterfall pallete color setting not restored after MSCC-PS is exited and restarted and the S/W screen is viewed.

### ISSUE THREAD

**Issue by Bob-TX** [w4mmp/MSCC-PW#17]
**Describe the bug**
The ENHANCED setting of pallette color for the waterfall in the S/W tab is not properly saved and restored when MSCC-PW is exited and then re-started.

**To Reproduce**
1. Run MSCC-PW, click on S/W and then click Enhanced in the waterfall pallette window. Observe the waterfall responds correctly with high-contrast multi-color display of signals.
2. Click S/W to close the spectrum/waterfall settings window. Observe the enhanced color still appears in the waterfall window.
3. Again click S/W to view the spectrum/waterfall settings window. Note that the enhanced color pallette setting for the waterfall is shown to be selected. Note that the waterfall properly shows the enhanced pallette.
4. Click S/W on the MAIN display to close the spectrum/waterfall settings window. Note that the enhanced color mode still displays in the waterfall screen.
5. Click EXT on the MAIN screen and click Yes to stop MSCC-PW and return to the Windows desktop.
6. Run MSCC-PW and observe the waterfall is properly displayed with the enhanced color pallette. 
7. Click S/W on the MAIN display to view the spectrum/waterfall settings window. Note that the waterfall display immediately changes back to the default red/yellow color pallette. Additionally on the S/W settings display Red/Yell waterfall color pallette is shown to be selected. 
**Expected behavior**
I expected all settings that are in use on the S/W settings display screen to be saved and then restored after MSCC-PW is exited and re-started. I did not expect any settings to be changed when I click S/W on the Main screen. In the numbered paragraphs above - I believe steps 1. through 6. are all normal, expected behavior. Only step 7. above shows unexpected behavior.

**MSCC-PW release date (please complete the following information):**
MSCC-PW: 09/07/2022

**Desktop (please complete the following information):**
 - OS: Windows 10 Home

**Additional context**

**Comment by w4mmp** [comment]
Hi Bob,
This issue has been resolved with a new release on the Google Drive: MSCC-PW-Install-20220919.exe
73,
Ron
