### ISSUE TITLE
AM model reception audio distorted with Low Cut filter settings of 200Hz, 300Hz or 500Hz.

### ISSUE THREAD

**Issue by Bob-TX** [w4mmp/MSCC-PW#18]
**Describe the bug*
The receiver audio is distorted in AM mode when the Low Cut filter setting is greater than 100Hz.

**To Reproduce**
1. Start MSCC-PW, select AM mode and tune in a strong broadcast station (9.980Mhz or a WWV frequency with good reception).
2. Click on the Low Cut Filter settings and listen to the received audio while each available setting is in use.
3. Note that the received audio is not properly demodulated/detected when the Low Cut filter in use is 200Hz, 300Hz or 500Hz.

**Expected behavior**
I expected the receiver audio to remain undistorted regardless of what Low Cut Audio filter is in use. 

**MSCC-PW release date (please complete the following information):**
MSCC: 09/07/2022

**Desktop (please complete the following information):**
 - OS: Windows 10 Home

**Additional context**
Note that the Low Cut filter settings are working properly as far as restricting the low-frequency (bass) range of receiver audio in both AM, LSB and USB modes. Even on a AM broadcast signal, listening with either LSB or USB receiver mode allows the use of all available Low Cut Filter settings with minimal audio distortion. I suspect that the algotithms used for Low Cut audio filtering are removing the carrier signal when 200Hz or greater is selected thereby causing distortion of the received audio in AM mode ONLY.

**Comment by w4mmp** [comment]
Hi Bob,
I will listen to AM this evening when WTWW comes on the air.  It is best to listen when full spectrum audio is transmitted.  I have heard the distortion in the past but I will give a good listen and let you know.
73,
Ron

**Comment by w4mmp** [comment]
Hi Bob,
Yes, there is distortion in AM mode.  I'm not sure if this will be resolved any time soon.  The person that wrote the DSP engine is not actively involved with Multus SDR.  But I will check with him.
73,
Ron
