### ISSUE TITLE
Alternative function of "KEY"  input in Mode USB, LSB (opt. AM)

### ISSUE THREAD

**Issue by HB9SIU** [w4mmp/MSCC-PW#20]
Hi Ron,

It was the intention of the software designer at MSCC to
that the socket "KEY", only exactly in the mode "CW" and at
active software key "PTT" a CW carrier at the RF output
is generated by Proficio.
In all other operating modes or inactive
"PTT" shows the socket "KEY-Input" no reaction.

topic 1
Inquiry , request for modification of the functioning of the "Key" socket

- In the MSCC application, in the operating modes USB, LSB (optional AM), with an active signal on "KEY" input,
 the software button "PTT" is activated. The TX is booted up.
In "CW" mode, the "KEY" input shows normal (unchanged) behavior.

Reason and intention:

The TX can be activated via KEY input by a hardware switch.
eg. PTT on the microphone, foot switch, VOX control or "CQ speech machine" in contests.

This option should be selectable -active or passive- by querying the program "Initialite.BAT".

topic 2
- Idea and thoughts about fashion "CW":

When the button is first activated (keyer), the TX is activated when the button is pressed, but NO CW carrier is sent out.

When the button is released, the TX remains active for 1-3 seconds with no CW sinal output.
After the above time has elapsed, TX off and RX active.
If the key is pressed a second time within the above time period, the CW carrier is transmitted in the rhythm of the key play, corresponding to the key play of the CW modulated HF carrier.
If the key play is interrupted for 2-n seconds, automatic return from TX to RX
Operation.

best 73 de HB9SIU,  John

**Comment by w4mmp** [comment]
Hi John,
Stew and I are reviewing your request.  We will let you know what our determination is.
73,
Ron

**Comment by HB9SIU** [comment]
Thank you very much
i hope the best for me... hi

73 de hb9siu

**Comment by HB9SIU** [comment]
Addendum to #20

Hello Stew, hello Ron,
Here are a few words of explanation for my request.

To topic 1

This application is of great interest to me here.
Complexity and effort for implementation: small (my guess)


To topic 2
My interest very small.
Was just an idea.
(I'm not a CW man, sorry)
Complexity and effort: high to very high. (My estimation)

Change to my first request:
Query whether this option #20 is active or passive,
  not in the program "initialize.bat"
but with the "First Boot" prog (mscc-pw-cfg.exe) similar to query "PCB Version" (komand-line window)

best 73 de HB9SIU, John

**Comment by HB9SIU** [comment]
shy question:
Is an access to the source by me
a possibility ?

HB9SIU,  John

**Comment by HB9SIU** [comment]
I think we can close this issue.

best regards  John  HB9SIU
