### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by BobW9BF** [w4mmp/MSCC-PW#21]
I installed the 10/14 release.  Initially, I had no issues other than restoring my calibration settings from a backup file did not work.  

I later experienced issues when restarting.  I would get several incomplete loadings of MSSC GUI.  After several retries the program would eventually load and the initial screen showing "30.000 000 Khz" and USB would revert to the last band and mode I used and all would be coordinated.  After prolonged use I sometimes experienced latency in mouse click responses.  Stop and restart would clear that up.

On the second day of using 10/14 MSCC-PW I could not get the GUI to respond.  Spectrum and waterfall loaded with sound and signals showing but the GUI did not fully load.  I could not produces a ziplog to send as a result.  I did attach a .jpg of the error message.

My thanks for fixing the first dropped dit.  Works fine when it works...

Bob W9BF

 
**MSCC-PW release date (please complete the following information):**   20221014
[e.q. 20220818]
![Error](https://user-images.githubusercontent.com/34874195/196009719-0383af66-13f4-4f6c-be8f-4a5f6d82d208.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]

**Additional context**

**Comment by w4mmp** [comment]
Hi Bob,
I believe this has been resolved with the installation of the proper .Net 4.8 Framework.  The latest MSCC-PW release now performs a check to verify the correct version is installed on the computer.
73,
Ron

**Comment by BobW9BF** [comment]
Ron,

I found I had NET version 4.8.3xxxx on my computer but I went to a
Microsoft site that had the October 11 update version for my ancient Win10
Pro v. 1604.  That update did the trick.  So far (fingers crossed) works as
advertised with all the features for flawless semi-break 30 wpm cw.
Returned here to "happy camper" status.

Thanks,
Bob

**Comment by w4mmp** [comment]
Hi Bob,
I'm really glad we have resolved your issues with MSCC-PW.  It was a rough start but I think we are there.  Enjoy the rig.

73,
Ron
