### ISSUE TITLE
Loss of frequency and band power level calibrations

### ISSUE THREAD

**Issue by BobW9BF** [w4mmp/MSCC-PW#23]
On occasion I have started MSCC-PW before the Ultimus is powered.  The result has been loss of calibration settings.  The Restore function under the System tab did not restore the calibrations.

**Comment by w4mmp** [comment]
Hi Bob,
This has been fixed.  MSCC-PW now cleanly (after acknowledging a couple of pop ups) shuts down.  MSCC-PW will not go to the routines that update the initialization files.
The new release will be available in a few days.
73,
Ron

**Comment by BobW9BF** [comment]
TU.  Glad the issue wasn’t caused solely by my computer. Bob On Nov 10, 2022, at 9:11 AM, W4MMP ***@***.***> wrote:﻿
Hi Bob,
This has been fixed.  MSCC-PW now cleanly (after acknowledging a couple of pop ups) shuts down.  MSCC-PW will not go to the routines that update the initialization files.
The new release will be available in a few days.
73,
Ron

**Comment by w4mmp** [comment]
Hi Bob,
This issue has been fixed.  Watch for a new release today.
