### ISSUE TITLE
VFO B frequency doesn't change

### ISSUE THREAD

**Issue by BobW9BF** [w4mmp/MSCC-PW#25]
Using the Beta feature to engage VFO B function has an issue when using a mouse to change frequency.  A change in frequency using a mouse produces a change in audio reflecting the change, but the console frequency digits do not.

In Beta mode VFO A does change the digital frequency display when the mouse is used.

**Comment by w4mmp** [comment]
Hi Bob,
Hum, I can't reproduce the issue here.  Was your mouse hovering over the volume control when you were attempting to change the frequency?

**Comment by w4mmp** [comment]
Or, was your mouse over the spectrum display.  I just discovered the VFO B frequency does not change when changing frequency via the spectrum display.

**Comment by BobW9BF** [comment]
Ron,I’ll try and repeat using your suggestion.  Appreciate your reply.  It’s no pressing issue but thought I’d pass along as I used the Beta version the first time.  BobOn Nov 10, 2022, at 9:15 AM, W4MMP ***@***.***> wrote:﻿
Hi Bob,
Hum, I can't reproduce the issue here.  Was your mouse hovering over the volume control when you were attempting to change the frequency?

**Comment by BobW9BF** [comment]
I just got back home and turned on the Ultimus and reread your email where
you did find the issue I put on Github.  I'm still seeing the digital
frequency not following the mouse click.  The mouse will change the
frequency so not a big issue not seeing it show up on the frequency readout.

**Comment by w4mmp** [comment]
What mouse _**click**_?  What are you clicking (a button)?  If so what button?

**Comment by BobW9BF** [comment]
Clicking on the spectrum to change frequency with left button. Sorry for not being clear but I thought you were a mind reader 🙂On Nov 10, 2022, at 2:18 PM, W4MMP ***@***.***> wrote:﻿
What mouse click?  What are you clicking (a button)?  If so what button?

**Comment by w4mmp** [comment]
OK, now I understand.  Nope, no mind reader here :)

**Comment by w4mmp** [comment]
Hi Bob,
This issue has been fixed.  Watch for a new release coming today.
73,
Ron
