### ISSUE TITLE
MSCC-PW allows transmit near but outside ham band frequency allocations.

### ISSUE THREAD

**Issue by Bob-TX** [w4mmp/MSCC-PW#26]
**Describe the bug**
MSCC-PW will allow transmitting CW on frequencies outside the FCC allocated US amateur radio bands. Please review the possible transmit frequency ranges to prevent possible illegal transmissions.

**To Reproduce**
1. Attach a transmitter dummy load and RF output meter to the transceiver. Adjust the HAM band to 160m and vary the MAIN tab frequency across the 1790 kHz to 1800 kHz range.
2. Select CW mode and momentarily select PTT and note RF output exists on 1792 through 1800 kHz frequencies.
3. Perform a second test while adjusting the MAIN tab frequency across the 2000 to 2025 kHz range.
4. Select CW mode and momentarily select PTT and note RF output exists on 2000 through 2022 kHz frequencies.
5. Note that US Amateur Radio Band frequency allocations for 160 meters are 1800 to 2000 kHz per chart at  https://www.arrl.org/files/file/Regulatory/Band%20Chart/Band%20Chart%208_5%20X%2011%20Color.pdf
6. A similar condition exists below and above the 80 meter HAM band frequency allocation.
7.  Note that the small red square that appears between the 10 kHz and 1 kHz digits in the VFO window of the MAIN tab in MSCC-PW does NOT indicate that transmit output is enabled or disabled. The red square does appear when frequencies outside the allocated ham band are tuned however the radio still produces transmit RF output until the tuning is adjusted significantly MORE outside the ham band range.
8. Please check all ham bands for these or similar symptoms.

**Expected behavior**
Transmit RF output should be disabled when selected frequency is NOT within US Amateur Radio frequency allocation.

I expected the red square in the VFO window on the main tab to indicate when a non-ham frequency was tuned AND the transmit function was disabled.

**MSCC-PW release date (please complete the following information):**
MSCC-PW-Install-20221124.exe

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
These symptoms exist without BETA TEST or TRANSVERTER boxes checked on the SYSTEM tab. I understand the TRANSVERTER function will allow transmit above 29.7 MHz up to 30 MHz for use with transverters.

Thank you!

**Comment by w4mmp** [comment]
Hi Bob,
I will make a change MSCC-PW to disable TX when out of band.  However, please remember that you as the control operator have the finial responsibility to operate your station in a manor consistent with your operating privileges and within the FCC rules and regulations.

**Comment by w4mmp** [comment]
Hi Bob,
I have made a change to MSCC_PW to prevent out of band transmission.  A new release will be available in a day or two.
73,
Ron

**Comment by Bob-TX** [comment]
Thank you, Ron. I'll continue the operators guide & checking for issues as
I get time.

Merry Christmas to you & your family.

Bob

**Comment by w4mmp** [comment]
Hi Bob,
MSCC-PW-Install-20221215.exe has been release.
Merry Christmas and may God Bless you.

**Comment by Bob-TX** [comment]
Thanks, Ron.

I'll check it out.

Merry Christmas to you & yours,

Bob

**Comment by Bob-TX** [comment]
Ron,
Please adjust the upper frequency limit for transmitting CW on the 60 Meter band to allow Channel 5 - 5405.0 kHz.
See .PDF file at https://www.arrl.org/files/file/Regulatory/Recommended_Practices_Version_6_5.pdf
for details.
The FCC regulations for 60 Meters specify five channels with different exact frequencies depending upon mode of transmission.
The current version of MSCC-PW (Jan 2023) won't allow CW operation on channel 5.
Thanks,
Bob, AF5Z
