### ISSUE TITLE
T/X IQ Frequency settings

### ISSUE THREAD

**Issue by zaxanoid** [w4mmp/MSCC-PW#27]
**Describe the bug**
in the IQBD settings in MSCC-PW, some of the bands don't display correctly, but the frequency does...see below   I clicked band to get 60m...it changed the freq to 5330500, but still says 80m

**To Reproduce**
1. Go to   P/M/IQ
2. Click on the box showing current band (e.g. 80m)
3. check top left box witgh frequency displayed. 
4. it appears that the first time you clikc on 80m, it still displays 80m, but the frequency changes to an appropriate one for 60m

**Expected behavior**
each click of the band, should change the text showing the next lowest band, and the frequency should change as well

**Screenshots**
![image](https://user-images.githubusercontent.com/7523085/211157396-0cc1067d-1a8a-48fb-afe3-d05b1d14a2c6.png)

**MSCC-PW release date (please complete the following information):**
version 20221227

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by w4mmp** [comment]
Hi,
This has been fixed in release MSCC-PW-Install-20230107.exe (on the Proton Drive).
BTW.  Nice issue report.  Exactly the way it should be :)
73,
Ron
