### ISSUE TITLE
Default & User Filter Settings not retained after program exit and restart

### ISSUE THREAD

**Issue by Bob-TX** [w4mmp/MSCC-PW#28]
The DEFAULT FILTERS on the Rx/Tx tab of MSCC-PW and the User Filter settings for VFO B on the Main tab are not stored upon program exit and restored upon program re-start.

To duplicate symptoms:
1. Run MSCC-PW and click Tx/Rx tab. Select DEFAULT FILTERS LOW to 300Hz, TX to 2.4KHz, HIGH to 2.4KHz and CW to 400Hz.
2. Return to MAIN tab and click EXT and then click YES to stop MSCC-PW.
3. Run MSCC-PW and click Tx/Rx tab. Observe the DEFAULT FILTERS TX has changed to 2.7KHz and CW has changed to 200Hz.

To duplicate symptoms for VFO B:
1. Run MSCC-PW, click System, click Beta Test & click OK to approve operating in Beta Test mode so that VFO B functions are available.
2. Set VFO A and VFO B User Filter settings on MAIN tab just below the frequency display to CW BANDWIDTH 400Hz, LO CUT filter to 300Hz and HI CUT filter to 2.4Khz.
3. Change ham band by clicking a different BAND SELECTION button on Main tab. Observe that the USER Filter settings revert to CW BANDWIDTH 200Hz, LO CUT to 75Hz and HI CUT to 300Hz.
4. The above conditions occur even if I set the DEFAULT and USER FILTER settings for both VFO A and VFO B on each of the ten bands - - Once I exit MSCC-PW and re-start it, my desired settings of CW BANDWIDTH 400Hz, LO CUT filter to 300Hz and HI CUT filter to 2.4Khz are lost particularly for VFO B.

The two symptoms above are likely related however I've been unable to understand or correct this response.

MSCC-PW version in use 01/02/2023, MS-sdr 2022.1202, SDRcore-recv 2022.1205, SDRcore-trans 2022.1109 and TRANSCEIVER 122.1.

Windows 10 Pro Version 22H2 with latest Windows updates in use.

Thank you for your diligence in correcting issues and adding features.
Bob, AF5Z

**Comment by w4mmp** [comment]
Hi Bob,
I will correct these issues, next week.
73,
Ron

**Comment by w4mmp** [comment]
Hi Bob,
The CW default filter issue is fixed.  As for the default TX default filter is not a "sticky" value.  I did this specifically so that operators are forced to make the decision to operator at larger than standard TX bandwidth every time MSCC-PW starts.  I can make the default 3Khz at MSCC-PW startup.  What do you think?  I will never allow the default TX bandwidth to be 5.5Khz. 

I'm still looking at the VFO B issue(s).
73,
Ron

**Comment by w4mmp** [comment]
Hi Bob,
All the issues have been resolved in release MSCC-PW-Install-20230123.exe except for the default TX bandwidth issue.  I will return to this at a later time.
73,
Ron
