### ISSUE TITLE
re-installation MSCC-PW not  possible

### ISSUE THREAD

**Issue by HB9SIU** [w4mmp/MSCC-PW#30]
From: HB9SIU e-mail: 3xc.trh@besonet.ch

Hi Bob, Ron and all

About 1 year ago I bought a Proficio and installed the necessary app "MSCC-PW" (MSCC-WINDOWS_Install-20230224.exe)  under "Win 10 pro".

After some initial difficulties, operation was possible.
Operation under GSDR was also OK.

After some experimentation with my PC and a careless operation on the operating system, much of the MSCC and GSDR installation was missing.
Despite intensive work on the PC, I can no longer put both apps "MSCC" and "GSDR" into operation.

1) The two "USB-Multus-Drivers" are installed. V 1.2.7.3 . Visible in Device Manager.

After double-clicking on the MSCC icon, the error message shown in Figure 1 appears.
This error message makes sense because the folders listed in the error message are not available.

The ZIP file that can be created with the app (?? sorry) is empty.
(Zip file is created but without content)

Any idea?

The "GSDR" app gets stuck during the installatiion in the "Initialize Genesis Radio Communication" phase. Stuck app can't with task manager
to be deleted.
Reboot necessary.

Thank you for any idea and help
best regards John

**Comment by HB9SIU** [comment]
![MSCC-PW](https://user-images.githubusercontent.com/45912766/234666593-322a4bfd-6832-4439-964c-debfa26ad14d.JPG)
![Multus control](https://user-images.githubusercontent.com/45912766/234666944-8073494f-f6c2-49ff-ba4a-93d9266a71b6.JPG)
![Multus  USB Audio](https://user-images.githubusercontent.com/45912766/234666993-cafad7bc-c940-4978-91d2-35bb58086fe9.JPG)


Figure 1  Top
LibUSB-Win32  driver

**Comment by HB9SIU** [comment]
HAM-Pc
Prozessor	AMD FX(tm)-4300 Quad-Core Processor               3.80 GHz
Installierter RAM	8.00 GB
Geräte-ID	8D452BCD-C800-4B13-9FAB-EAE06EA73D1E
Produkt-ID	00330-80000-00000-AA878
Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor
Stift- und Toucheingabe	Für diese Anzeige ist keine Stift- oder Toucheingabe verfügbar.



Edition	Windows 10 Pro
Version	22H2
Installiert am	‎14.‎10.‎2021
Betriebssystembuild	19045.2846
Leistung	Windows Feature Experience Pack 120.2212.4190.0

**Comment by HB9SIU** [comment]
Text above is Sys-Info

**Comment by HB9SIU** [comment]
[ms-sdr.zip](https://github.com/w4mmp/MSCC-PW/files/11345901/ms-sdr.zip)
[Multus_mscc.zip](https://github.com/w4mmp/MSCC-PW/files/11346050/Multus_mscc.zip)
[sdrcore-recv.zip](https://github.com/w4mmp/MSCC-PW/files/11346055/sdrcore-recv.zip)
[sdrcore-trans.zip](https://github.com/w4mmp/MSCC-PW/files/11346060/sdrcore-trans.zip)


1. As already mentioned above, the "Backup-logfiles.exe" file in the folder C:/MSCC-PW/utilitis" does not look for any log files for the zip file.
2.  I have listed  several zip files original log files from the 
folder..."C:\Users\Hans\AppData\Local\multus-sdr-mfc" here above.
3. I notice that this folder is named "-MFC". contains.
Does that matter. My Proficio has no "MFC". 
4. There is an error message in one of the log files.

I hope it helps you.

73 de HB9SIU, John

**Comment by w4mmp-ron** [comment]
Hi John,
I see this in your issue report:
![234666593-322a4bfd-6832-4439-964c-debfa26ad14d](https://user-images.githubusercontent.com/111645397/234982160-be9b4278-e4d5-46fe-bf4b-0ea3af0f8579.JPG)

Did you run the "initialize.bat" file in the release folder?  Even if you have, please run it again.

**Comment by HB9SIU** [comment]
Hi Ron,
Thanks a lot for your quick answer.
His reference to the "initialize.bat" file was successful.
Unfortunately not enough.
The main window, spectrum and waterfall will pop up. In the main window, the notice flashes during initialization.
After a few seconds, the error messages below appear. I think it is clear to you that no information appears in the "Spectrum and Waterfall" diagrams either. Also no sound output.

best 73 de hb9siu, John


![Error-msg](https://user-images.githubusercontent.com/45912766/235106600-95bd1222-d8ca-4da2-b78d-b7b537a642df.JPG)
![Lepal-error](https://user-images.githubusercontent.com/45912766/235106638-9a17aec8-ef5f-4018-a4e6-a2ca94a2ecc3.JPG)

**Comment by HB9SIU** [comment]
[ziplog.zip](https://github.com/w4mmp/MSCC-PW/files/11352184/ziplog.zip)

IMPORTANT  File

**Comment by HB9SIU** [comment]
Hello Ron.

MSCC-Pw is correct installed and running.
Many thanks for your help
Best regards and 73 de hb9siu,  John

I think we can close this issue.

**Comment by w4mmp-ron** [comment]
Hello John,
Glad it is working.
