### ISSUE TITLE
Lost semi-break cw with 20220820 update

### ISSUE THREAD

**Issue by BobW9BF** [w4mmp/MSCC-PW#4]
Previous version dated 8-18 had flawless semi-break cw.  Lost that function with new update.  Also, long-standing issue of meter function (only A and T buttons turn red and only S units displayed on meter).

Thanks, Bob W9BF
  
 
[ziplog.zip](https://github.com/w4mmp/MSCC-PW/files/9387728/ziplog.zip)

**Comment by w4mmp** [comment]
Hi Bob,
It works fine here.  Are you sure semi break in is set?  

Yes, only A and T are enabled since there is no Rego attached to the PC (and therefore no MFC or power meter).  

73,
Ron Patton

**Comment by BobW9BF** [comment]
Ron,

Thanks for the feedback.  Perhaps the installation had a glitch.  I’ll give it a try.  I did have semi-break in checked.  

Did the logs confirm anything?   

I asked Stew if I could go back to 20220818 which worked fine.  I’m concerned it will cause an issue with calibration settings.  Will it?  

Love the new MSCC.  i have a Flex 6600 and an LP-PAN for my K3.  Now it’s hard to operate without a panadapter.  

Many thanks to you and Stew for your contributions to making the hobby fun. 

73, Bob W9BF

**Comment by w4mmp** [comment]
Hi Bob,
Thanks!  I'm glad you like the new MSCC.  
Yes, You can go back to the previous release.  It will not effect any of your calibration or other settings.   I have not taken a look at the logs as yet.

**Comment by w4mmp** [comment]
The semi break in issue has been resolved.  No defect in MSCC-PW.
