### ISSUE TITLE
Downgrade failure

### ISSUE THREAD

**Issue by BobW9BF** [w4mmp/MSCC-PW#5]
Ron,

I verified this morning that 20220820 still would not do semi-bread cw.  So I reinstalled 20220818 without deleting the firmware files.  TUNE would work as always but again semi-break didn't.  I shut down and restarted and got an initialization failure message so per the error suggestion I'm attach the logs zip file for a suggestion on how to proceed.

I could always delete everything and start over but that recalibration procedure is something I'd like to avoid.

Many thanks for assistance.
Bob W9BF
[ziplog.zip](https://github.com/w4mmp/MSCC-PW/files/9389653/ziplog.zip)

**Comment by w4mmp** [comment]
Hi Bob,
Please install the current release.  Let's figure out what is wrong with the current release.
73,
Ron

**Comment by BobW9BF** [comment]
Ron,

After 20220818 didn't work, I went back to 20220820.  I got the
initialization error.  Then lost audio so shut down.  After reading your
instruction to reinstall the latest, and having already reinstalled, I
turned back on and got a sdr-trans.exe error message.  Before the MSCC shut
down automatically, I created a zip file which is attached.

It looks like I'm stuck so while you're perusing the logs, I'm going to
erase the MSCC-PW folder and start over with the latest firmware version
and face the music about recalibrating.

I'm determined to get things back working like they're supposed to.  It may
be I have to go to another computer but all my antennas are tied in with a
station control GUI that ties all radios into all antennas and
peripherals.  I'd love to use the Ultimus in my integrated station.  But,
there may be software conflicts with the Flex being on the same computer.
Lots of Flex virtual cables show up on MSCC menus.

 Thanks for helping me out, Ron..

Bob 'BF

**Comment by BobW9BF** [comment]
Ron,

This morning I did a fresh install of 20220820, ran the initialize.bat,
then MSCC-PW.  Immediately got the .....core-trans.exe error.  Attaching
zip file which shouldn't be too cluttered with attempts to correct.

Sorry for the trouble.  Before I hear from you, I'll uninstall and attempt
a fresh of 20220818.

Thanks, Bob W9BF
