### ISSUE TITLE
CW/AUDIO tab -> CW Controls -> PITCH frequency selection not persistent & has no effect on received filtering.

### ISSUE THREAD

**Issue by Bob-TX** [w4mmp/MSCC-PW#7]
**Describe the bug**
Changing the PITCH frequency to something other than the default 600Hz has no effect on the pitch of received signals and any changes made are not persistent i.e. when MSCC-PW is restarted, the desired setting is lost and the default 600Hz is shown.

**To Reproduce**
1. Click on CW/AUDIO tab in MSCC-PW console window.
2. Click on the up or down arrow to the right of '600Hz' that appears in the CW Control area of the screen below PITCH. Alternate PITCH frequecies of 400Hz, 500Hz, 700Hz or 800Hz can be selected. I note that the UP and DOWN arrows change the setting the opposite direction than expected, i.e. clicking the UP arrow makes the selection move DOWN in PITCH frequency. Leave the setting on anything other than the default of 600Hz.
3. Click on the MAIN tab to return to the console window. Click on EXT to stop the MSCC-PW program and close all windows.
5. Run MSCC-PW again by double-clicking the icon on the desktop to start the program. Again select CW/AUDIO tab and observe that the previously chosen PITCH frequency in the CW Controls area of the display again reflects 600HZ instead of the previously preferred PITCH frequency choice.

**Expected behavior**
I can not detect any change in the behavior of the receiver regardless of the chosen PITCH frequency. I expected an 800Hz PITCH when used with 200Hz CW filter bandwidth to allow me to hear audio frequencies from 700Hz to 900Hz as I slowly tune across a signal. I also tried to select a PITCH frequency of 400Hz which in my opinion should allow me to hear audio pitch frequencies of 300Hz to 500Hz when a 200Hz CW filter bandwidth is in use. With either a 400Hz or a 800Hz PITCH setting I hear the same audio pitch frequencies as I tune across a signal with a narrow 200Hz bandwidth CW filter in use.

**MSCC-PW release date **
MSCC-PW was installed with "MSCC-PW-Install-20220829.exe". The SYSTEM tab shows MSCC 08-29-2022.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Version 21H2 OS Build 19044.1889 with all current windows updates.

**Additional context**
The PITCH setting also impacts a CW operators ability to correctly SPOT the transceiver so that transmit and receiver frequencies match. Often an operator will set their CW sidetone audio frequency (pitch) to their preference to act as a reference guide to help correctly tune in a signal so that their transmitted frequency will match the frequency of the received signal.

**Comment by w4mmp** [comment]
Hi Bob,
When you scrolled in the list box the the tone you wanted, did you click on it?  To select a tone, you need to click on the value in the list box.
73,
Ron

**Comment by Bob-TX** [comment]
Hi Ron,

No I did not, and that resolves much of this bug report.

I now find that after I change the Pitch frequency to something other than 600Hz, if I click on the frequency value in the window the background returns to blue as it was before I changed the pitch frequency. This does cause the choice to be put in effect and the audio pitch of signals are changed to the new selected value. Additionally this new selected pitch frequency IS persistent after MSCC-PW re-starts.

--------------

Recommended change to Page 29 of MSCC-PW Operators Guide Revision Date 08-25-22

REPLACE:    4. PITCH. This is the CW side tone that is heard when when in receive mode (RX).

WITH:        4. PITCH. Select your preferred received CW audio tone frequency or pitch when a signal is centered in the filter pass band. Click the UP ARROW or DOWN ARROW to the right of the displayed PITCH value to change and then click on the window showing your chosen value to apply the change.

------------

The only remaining portion of the original bug report that is valid  is that the UP and DOWN arrows used to change the PITCH frequency move opposite of what I expected. This minor cosmetic function won't likely cause any trouble since users will click both UP and DOWN arrows to see what PITCH frequency choices are available. You may close this GitHub bug issue report or if you wish, I will.

Thank you,

Bob

**Comment by w4mmp** [comment]
Hi Bob,
This has been addressed.  In Windows GUI terms, the list box has been replaced with the a combo box.  Now when you click on the pitch combo box, a drop down list is presented.  Click on the tone you want.  That's it for changing the pitch.  Over the course of time, I will be replacing all list boxes with either combo boxes or simple multi click buttons that change the displayed value with each click of the button.

The operators guide has been updated to say this: 4. PITCH. Select your preferred received CW audio tone frequency or pitch when a signal is centered in the filter pass band. 

Using the combo box should be obvious for most users.

73,
Ron
W4MMP

**Comment by Bob-TX** [comment]
Thank you very much for promptly and completely resolving this issue.
Best Regards,
Bob
