### ISSUE TITLE
SET LOW CUT FILTER labels incorrect for 300Hz and 500Hz selections.

### ISSUE THREAD

**Issue by Bob-TX** [w4mmp/MSCC-PW#8]
**Describe the bug**
The on-screen label for the 300Hz and 500Hz LOW CUT FILTER settings shows 300kHZ and 500kHZ.

**To Reproduce**
1. Run MSCC-PW and identify the SET LOW CUT FILTER button just below the 100kHZ digit of the frequency display.
2. Click on the SET LOW CUT FILTER button multiple times to move through all available choices and observe the displayed settings.
3. Note that the 75Hz, 100Hz and 200Hz settings are shown correctly as Hz.
4. Note that the settings show 300kHz and 500kHz when chosen. This should be 300Hz and 500Hz.

**Expected behavior**
I expected the available LOW CUT FILTER frequency settings to be in the lower range of human hearing. The software provides a range of 75Hz to 500Hz which is good but the label for 300Hz and 500Hz is incorrect. The function of the filters sounds correct.

**MSCC-PW release date (please complete the following information):**
MSCC 09/01/2022

**Desktop (please complete the following information):**
 - OS: Windows 10 Home

**Comment by w4mmp** [comment]
Hi Bob,
Thanks for catching this.   It has been fixed.  New release on the Google Drive.
73,
Ron

**Comment by Bob-TX** [comment]
Thank you!

**Comment by w4mmp** [comment]
Hi Bob,
The issue is fixed.  New release on the Google Drive.
73,
Ron
