### ISSUE TITLE
12m FAVS show on 10m and cause .NET error

### ISSUE THREAD

**Issue by Bob-TX** [w4mmp/MSCC-PW#9]
**Describe the bug**
Unable to ADD or DELETE 12m band FAVORITES. I attempted to add a single favorite on each band 20m, 17m,, 15m, 12m and 10m for the NCDXF International Beacon System (see https://www.ncdxf.org/beacon/beaconlocations.html). I was able to create a favorite named INTL BCN on bands 20m, 17m, 15m and 10m however attempts to create a 12m favorite failed as described below.. 

**To Reproduce**
1. Tune to a 12m frequency 24.930 MHz. Click on Favs tab in MSCC-PW. 
2. Click on Enter Name and type in desired name (I used INTL BCN). Click ADD. Observe that newly created favorite appears in the 10m band favorites area and .NET error occurs. See screen grab below.
3. I tried multiple times to prevent the error but any 12m favorites I create appear in 10m area. 
4. Additionally I'm unable to DELETE these 12m frequencies from the 10m favorites area. This action also creates a .NET error (see screen grab).

**Expected behavior**
I expected to be able to ADD and DELETE favorites in each band as I did on bands other than 12m.

**Screenshots**
![12m Favs ADD causes  NET error](https://user-images.githubusercontent.com/112591395/188225915-cf30e77c-67b3-4f51-a78f-6c2d73c444f0.JPG)

**MSCC-PW release date (please complete the following information):*
MSCC 09/02/2022

**Desktop (please complete the following information):**
 - OS: Windows 10 Home

**Additional context**
I note that the 'b12_favs.ini' file in folder \MSCC-PW\backup is an empty file (0 bytes) while similiarly named files for other bands contain data. This is also true for that file in folder \MSCC-PW\init-files\.local\share\mscc and also in path \MSCC-PW\utilities\backup. Perhaps this contributes to this failure.

**Comment by w4mmp** [comment]
Hi Bob,
Thanks for giving MSCC-PW a good shake down.  Actually have been waiting for someone to give it a good one.
I will look into this issue tomorrow.  
73,
Ron

**Comment by w4mmp** [comment]
Hi Bob,
This has been fixed.  New release on the Google Drive.
73,
Ron
